// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBB0Ea5sU0AmLPanjj9hJXJfkomhnxf9PQ',
    appId: '1:744301719503:web:f12177d73af5727aa2acba',
    messagingSenderId: '744301719503',
    projectId: 'flutter-2981b',
    authDomain: 'flutter-2981b.firebaseapp.com',
    storageBucket: 'flutter-2981b.appspot.com',
    measurementId: 'G-QVFRB0GQ87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoixlMV9j52pD7ZJ8ajMeIzcrP8CQwfuQ',
    appId: '1:744301719503:android:17fa24a950b45f0ca2acba',
    messagingSenderId: '744301719503',
    projectId: 'flutter-2981b',
    storageBucket: 'flutter-2981b.appspot.com',
  );
}
